#!/bin/bash -e

# A simple script to generate a SVG road shield.
# Copyright 2014 Paul Norman
# Released under the Creative Commons CC0 license

# Syntax
# ./create_shield colour width height xoffset yoffset

# Fixed values
RADIUS=3
OUTERLINE=1.5

COLOUR=$1
WIDTH=$2
HEIGHT=$3


echo "<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' "\
"viewBox='0 0 $(bc -q <<< "$WIDTH") $(bc -q <<< "$HEIGHT")'>"

echo "<rect x='0' y='0' height='$HEIGHT' width='$WIDTH' rx='$RADIUS' fill='$COLOUR'/>"

echo "<rect x='$(bc -q <<< "$OUTERLINE")' y='$(bc -q <<< "$OUTERLINE")' "\
"height='$(bc -q <<< "$HEIGHT - 2*$OUTERLINE")' width='$(bc -q <<< "$WIDTH - 2*$OUTERLINE")' "\
"rx='$(bc -q <<< "$RADIUS - $OUTERLINE")' fill='white'/>"

echo "</svg>"
